### ISSUE TITLE
Git annex initremote ImportError: No module named 'pcloudapi'

### ISSUE THREAD

**Issue by cdanger** [tochev/git-annex-remote-pcloud#1]
Hello,
I got the error below when trying to initialize the special pcloud remote:

```
$ git annex initremote my.pcloud type=external externaltype=pcloud encryption=hybrid keyid=31ECBEE4 path=test credentials_file=~/.pcloud_auth
initremote my.pcloud (encryption setup) (hybrid cipher with gpg key EC083AC131ECBEE4) Traceback (most recent call last):
  File "/usr/bin/git-annex-remote-pcloud", line 23, in <module>
    from pcloudapi import PCloudAPI, PCloudException
ImportError: No module named 'pcloudapi'
git-annex: external special remote protocol error, unexpectedly received "" (unable to parse command
```

I guess we are expected to install pcloudapi module first, aren't we?
Could you give instructions to do that, and update the README?
Thank you.

Regards,
Cyril

**Comment by tochev** [comment]
Hi, thanks for reporting that :)

It seems that I had a bug that prevented the `git-annex-remote-pcloud` script from correctly detecting the pcloudapi library location when using symlinks.

It is now fixed (in f0a22bee9ae081689db3cbca0a8616950e9953a0 ), so if you do a `git pull` you should be good to go.

I have also included instructions in the README on how to install the python3 pcloudapi library globally, but I do not recommend it.

I'm marking the issue as resolved. Please feel free to reopen it if the above does not fix your problem :)
