### ISSUE TITLE
different locations for credentials_file

### ISSUE THREAD

**Issue by disteph** [tochev/git-annex-remote-pcloud#2]
Great tool for git-annex! I have a set-up where two computers (each hosting a git-annex repo) want to access the same pcloud special remote. Unfortunately, the credentials_file cannot be at the same location on the two computers (I have different home paths), so if the value of the credentials_file parameter (when doing initremote or enableremote) is fixed for the UUID, being kept in remote.log in the git-annex branch, then only one of my computers can get it. What would you suggest for this? Would it be possible to keep the credentials_file parameter in git's config file instead?

**Comment by tochev** [comment]
I'm not sure that I understand correctly your use case and respectively your question, but if it is how not to store the `credentials_file` configuration then you could use `PCLOUD_CREDENTIALS_FILE` environment variable during initialization/enabling of the remote. Internally it fetches an authorization token from pcloud and uses git annex's `SETCREDS` functionality to store it (see https://git-annex.branchable.com/design/external_special_remote_protocol/ for more information and security implications).

The example below should correspond to what I believe is your use case.
In this example there are two folders `A` and `B` representing two computers, a shared pcloud remote and files are transferred between them through pcloud (`1.txt` from `A` and `2.txt` from `B`)

```!bash
#!/bin/bash
set -e
set -x

AUTH=~/.pcloud_auth_for_testing  # original auth file
TESTDIR="$(dirname $0)"
TESTFOLDER=$RANDOM

cd "$TESTDIR"
export PATH="$PWD/../:$PATH"  # for path to git-annex-remote-pcloud

# clear the test area
chmod u+w -R playground || true  # during tests some files are created with u-w, so make sure they are deletable
rm -rf playground || true  # clear test area

# create two folders for two repos (mimics two different computers)
mkdir -p playground/{A,B}/

# make two copies of the credentials file as if on two computers
cp "$AUTH" playground/a.auth
cp "$AUTH" playground/b.auth

# initialize location A
cd playground/A/
git init && git annex init "placeA"
# next - init pcloud special remote, while storing auth token taken from pcloud using SETCREDS
#    see https://git-annex.branchable.com/design/external_special_remote_protocol/ (search for SETCREDS)
PCLOUD_CREDENTIALS_FILE="../a.auth" git annex initremote mypcloud type=external externaltype=pcloud \
    path=/test_git_annex/$TESTFOLDER \
    encryption=none embedcreds=no
rm ../a.auth  # we no longer have access to the auth file

# create sample file, add it to git annex and move it to pcloud
echo 1 > 1.txt
git annex add *
git commit -m 'Add 1.txt' -a
git annex move * --to mypcloud  # move the file to pcloud
test ! -e 1.txt  # 1.txt does not exist anymore

# initialize location B
cd ../B/
git init && git annex init "placeB"
git remote add placeA ../A/

cd ../A/
git remote add placeB ../B/
git annex sync  # sync folders A and B

# continue with B
cd ../B/
git annex sync
# next - enable mypcloud special remote while storing auth token taken from pcloud
PCLOUD_CREDENTIALS_FILE="../b.auth" git annex enableremote mypcloud embedcreds=no
rm ../b.auth  # we no longer have access to the auth file
test ! -e 1.txt  # 1.txt does not exist
git annex get 1.txt --from mypcloud  # fetch 1.txt
cat 1.txt  # outputs 1, the file was copied to B

# add a new file in B, move it to pcloud, and fetch it in A
echo 2 > 2.txt
git annex add *
git annex move 2.txt --to mypcloud
git commit -m 'Add 2.txt'
test ! -e 2.txt  # 2.txt does not exist anymore
cd ../A/  # back in A
git annex sync
test ! -e 2.txt  # 2.txt does not exist
git annex get 2.txt --from mypcloud
cat 2.txt  # outputs 2 - the file was copied to A

echo "DONE"
```

Please let me know if this solves your problem.

**Comment by disteph** [comment]
Thanks for the very detailed reply! Yes, my problem was that the credentials_file parameter was recorded in the remote.log file of the git-annex branch, but its value had to be different on different computers.
Not setting it but using the environment variable PCLOUD_CREDENTIALS_FILE instead solves my issue because I can set it differently on different computers. And indeed it only seems to be used once, to retrieve the token and place it in the .git/annex/creds directory. This works for me. Thanks again!

**Comment by tochev** [comment]
No problem, glad to be of help :)
